splitter = "\n----------\n"

# Warm-up: String Basics
# Create two variables called first_name and last_name and assign them
# your own values.
# Your program must now do the following:
# 1. Concatenate first_name and last_name into one string called full_name,
# separated by a space.
# 2. Print full_name.
# 3. Print the length of full_name.
# 4. Print full_name in all uppercase letters.
# 5. Check whether the letter “a” appears in full_name and print the result.
# Hint: Look back at the Strings slides for the relevant string methods

first_name, last_name = "Daniel", "Hansen"
full_name = f"{first_name} {last_name}"
# Or
full_name_long = first_name + " " + last_name
print(f"Full name short version:\n{full_name}\nFull name long version\n{full_name_long}\n")
print(full_name_long.upper())
print("a" in full_name)


print(splitter)
"""--------------------------------------------------------"""


# String Slicing - Usernames
# You are given the following username, generated by a security
# system:
# Your program must now do the following:
# 1. Print the first 5 characters of username using slicing.
# 2. Print the last 4 characters of username using slicing.
# 3. Print username reversed using slicing.
# 4. Break username into its three parts and print the resulting list.
# 5. Put the three parts back together, this time separated by a dash (-)
# instead of an underscore.

username = "admin_liban_2026"



print(username[:5])
print(username[-4:])
print(username[::-1])
username_split = username.split("_")
print(username_split)
username_new = "-".join(username_split)
print(username_new)



print(splitter)
"""--------------------------------------------------------"""

# Number Crunching - Login Attempts
# A firewall logged the following number of failed login attempts on three
# separate days:
day1 = 12
day2 = 40
day3 = 8
# Your program must now do the following:
# 1. Calculate the total number of attempts across the three days and store it in a
# variable called total.
# 2. Print total.
# 3. Calculate the average attempts per day using division and print it.
# 4. Use integer division (//) to find out how many full sets of 10 attempts happened in
# total.
# 5. Use the modulus operator (%) to find out how many attempts are left over after
# those full sets of 10.

total = day1 + day2 + day3
print(f"total logins: {total}")
print(f"average attempts per day: {total/3}")
print(f"full sets of 10 attempts: {total//10}")
print(f"left after 10: {total%10}")



print(splitter)
"""--------------------------------------------------------"""

# Boolean Access Check
# Create three boolean variables representing the state of a user
# session:
has_mfa = True
is_admin = False
session_expired = True
# Your program must now do the following:
# 1. Using logical operators (and, or, not), compute whether the user should be
# granted access: they need MFA enabled AND the session must NOT be expired.
# Store the result in a variable called access_ok and print it.
# 2. Bonus: Use if/else statement, print “Access Granted” or “Access Denied” based
# on access_ok.
# 3. Bonus Bonus: add a check that prints “Admin Override” if the user is an admin,
# regardless of the other two values.

access_ok = has_mfa and not session_expired
print(access_ok)
if is_admin: print("Admin Override")
elif access_ok: print("Access Granted") 
else: print("Access Denied")



print(splitter)
"""--------------------------------------------------------"""

# List Basics - Blocked Ports
# Create a list called blocked_ports with the following values:
blocked_ports = [21, 23, 135, 445]
# Your program must now do the following:
# 1. Print the first port in the list.
# 2. Print the last port in the list using negative indexing.
# 3. Add the port 3389 to the end of the list.
# 4. Remove the port 23 from the list.
# 5. Sort the list in ascending order and print the result.

print(f"First port: {blocked_ports[0]}")
print(f"last port: {blocked_ports[-1]}")
blocked_ports.append(3389)
print(f"updated port list: {blocked_ports}")
blocked_ports.remove(23)
# Or
# blocked_ports.pop(1)
# Or
# del blocked_ports[1]
blocked_ports.sort()
print(f"ascending order {blocked_ports}")
blocked_ports.sort(reverse=True)
print(f"descending order {blocked_ports}")



print(splitter)
"""--------------------------------------------------------"""

# Network Scan Statistics
# Make a list containing these values:
response_times_ms = [45, 120, 38, 201, 89, 156, 72, 93, 167, 54]
# Your program should:
# 1. Print how many hosts were scanned (length of list)
# 2. Calculate the total response time (sum of all values)
# 3. Calculate the average response time
# 4. Find the fastest response time
# 5. Find the slowest response time
# 6. Bonus: Count how many responses were faster than 100ms (hint: use loop)
# 7. Bonus: Create a new list with all response times divided by 2
# Note: For task 6 and 7 you need knowledge haven’t covered yet.
# Hint: sum(), min(), max(), list comprehension (optional)

hosts_scanned = len(response_times_ms)
print(f"Hosts scanned: {hosts_scanned}")

total_response_time = sum(response_times_ms)
print(f"Total response time: {total_response_time}")

print(f"average response time: {total_response_time/hosts_scanned}")
print(f"fastest response time: {min(response_times_ms)}\nslowest response time: {max(response_times_ms)}")

under_100 = 0
new_list = []
for time in response_times_ms:
    if time < 100: under_100 += 1
    new_list.append(time/2)

print(f"Under 100ms: {under_100}")
print(f"new list diveded by 2: {new_list}")



print(splitter)
"""--------------------------------------------------------"""

# List Slicing - Trimming the Log
# You are given the following list of the last 10 log entry IDs:
log_ids = [101, 102, 103, 104, 105, 106, 107, 108, 109, 110]
# Your program must now do the following:
# 1. Use slicing to print the first 3 log_ids.
# 2. Use slicing to print the last 2 log_ids.
# 3. Use slicing to print every second log_id, starting from the first.
# 4. Use slicing to print the list in reverse order. (DON’T USE .reverse())
# 5. Create a new list called recent_logs containing only the last 4
# elements of log_ids.

print(f"First 3 entries: {log_ids[:3]}")
print(f"last 2 entries: {log_ids[-2:]}")
print(f"every 2nd entries: {log_ids[::2]}")
print(f"reverse entries: {log_ids[::-1]}")

recent_logs = log_ids[-4:]
print(f"entries from recent_logs: {recent_logs}")



print(splitter)
"""--------------------------------------------------------"""

# List Methods - Password Attempts
# You are tracking failed password attempts per session in the
# order they occurred:
attempt_counts = [1, 3, 2, 1, 5, 3]
# Your program must now do the following:
# 1. Find out how many times the value 3 appears and print it.
# 2. Find the index of the first 5 in the list and print it.
# 3. Add the value 2 to the list.
# 4. Sort the list in ascending order and print it. (E.g. 1,2,3 etc.)
# 5. Reverse the sorted list and print it.

print(f"3 appears {attempt_counts.count(3)} times")
print(f"5 has the index {attempt_counts.index(5)}")
attempt_counts.append(2)

attempt_counts.sort()
print(f"List sorted {attempt_counts}")
attempt_counts.reverse()
print(f"List reversed {attempt_counts}")



print(splitter)
"""--------------------------------------------------------"""

# Tuple Basics - Server Info
# Create a tuple called server_info with the following values:
server_info = ("10.0.0.15", 443, "web01")
# Your program must now do the following:
# 1. Print the port using indexing.
# 2. Try to change the port to 8443 by assigning to server_info[1]. Run it
# and note what happens.
# 3. Convert server_info into a list called server_info_list.
# 4. Update the port in server_info_list to 8443.
# 5. Convert server_info_list back into a tuple called server_info_updated
# and print it.

print(f"port: {server_info[1]}")

# TyeError because tuples are immutable
# server_info[1] = 8443
server_info_list = list(server_info)
server_info_list[1] = 8443
server_info_updated = tuple(server_info_list)
print(f"updated tuple: {server_info_updated}")



print(splitter)
"""--------------------------------------------------------"""

# Tuple Trouble - Adding a Value
# Start by declaring the following tuple:
users = ("liban", "laura", "alex")
# Your program must now do the following:
# 1. You realize the tuple is missing the value “jim”. Add it without
# hardcoding a brand new tuple – use concatenation instead.
# 2. Print the updated tuple.
# 3. Print how many users are now in the tuple.
# 4. Check whether “luise” is in the tuple and print the result.

users = users + ("jim",)
print(f"updated tuple {users}")

print(f"number of users: {len(users)}")

print(f"Luise is in the tuple: {"luise" in users}")



print(splitter)
"""--------------------------------------------------------"""

# Dictionary Basics - Access Levels
# Start your program with the following dictionary:
access_levels = {"liban": "admin", "laura": "admin", "guest1": "read-only"}
# Your program must now do the following:
# 1. Print the access level of laura.
# 2. Safely try to access guest2 so your program doesn’t crash if the key doesn’t
# exist.
# 3. Update guest1’s access level to “read-write”.
# 4. Add a new entry for “alex” with the access level “moderator”.
# 5. Delete guest1 from the dictionary.
# 6. Print the final dictionary.

print(f"Access level of Laura: {access_levels["laura"]}")
print(f"Trying to access guest2: {access_levels.get("guest2")}")
access_levels["guest1"] = "read-write"
# Or
# access_levels.update({"guest1": "read-write"})
access_levels.update({"alex": "moderator"})
print(f"Updated dict: {access_levels}")

access_levels.pop("guest1")
print(f"Final dict: {access_levels}")



print(splitter)
"""--------------------------------------------------------"""

# Nested Dictionary - Asset Inventory
# Start your program with the following nested dictionary:
assets = {"srv01": {"os": "Linux", "patched": True},
          "srv02": {"os": "Windows", "patched": False}}
# Your program must now do the following:
# 1. Print the operating system of “srv01” using nested key access.
# 2. Change the “patched” status of “srv02” to True.
# 3. Add a brand new asset “srv03” of your choosing, with its own os and
# patched values.
# 4. Print how many assets are currently in the dictionary.
# 5. Print the final assets dictionary.

print(f"srv operating system: {assets['srv01']['os']}")
assets['srv01']['patched'] = True
assets.update({"srv03": {"os": "MacOS", "patched": False}})

print(f"assets avaliable: {len(assets)}")
print(f"Final assets dict: {assets}")



print(splitter)
"""--------------------------------------------------------"""

# Set Basics - Allowed IPs
# Create a set called allowed_ips with the following values:
allowed_ips = {"10.0.0.1", "10.0.0.2", "10.0.0.3"}
# Your program must now do the following:
# 1. Add “10.0.0.4” to the set.
# 2. Check if “10.0.0.5” is in the set and print the result.
# 3. Remove “10.0.0.2” from the set.
# 4. Print how many IPs are currently in the set.
# 5. Print the final set.

allowed_ips.add("10.0.0.4")
print(f"ips: {allowed_ips}")
print(f"10.0.0.5 is in the set: {"10.0.0.5" in allowed_ips}")
allowed_ips.discard("10.0.0.2")
print(f"ips: {allowed_ips}")



print(splitter)
"""--------------------------------------------------------"""

# Set Operations - Threat Intel Feeds
# You receive malicious IP addresses from two different threat
# intel feeds:
feed_a = {"1.1.1.1", "2.2.2.2", "3.3.3.3"}
feed_b = {"2.2.2.2", "3.3.3.3", "4.4.4.4"}
# Your program must now do the following:
# 1. Find the IPs that appear in BOTH feeds using intersection and print
# them.
# 2. Combine both feeds into one set of all known malicious IPs using union
# and print it.
# 3. Find the IPs that are only in feed_a and not in feed_b using difference
# and print them.

in_both = feed_a.intersection(feed_b)
print(f"In both feed: {in_both}")
feed_ab = feed_a.union(feed_b)
print(f"Feeds united: {feed_ab}")
not_in_a = feed_a.difference(feed_b)
print(f"only in feed a: {not_in_a}")



print(splitter)
"""--------------------------------------------------------"""

# Mixed Practice - Login Report
# You are given the following list of login records, one dictionary per login:
logins = [{"user": "admin", "ip": "10.0.0.5"},
          {"user": "admin", "ip": "192.168.1.10"},
          {"user": "guest", "ip": "10.0.0.5"}]
# Your program must now do the following (no for loops yet – access each item manually with
# logins[0], logins[1], etc.):
# 1. Create an empty set called unique_ips.
# 2. Add the “ip” value from each of the three logins to unique_ips, one at a time.
# 3. Print how many unique IPs attempted a login.
# 4. Create an empty dictionary called login_counts.
# 5. Add “admin” to login_counts with a value of 1.
# 6. Since the second login shows “admin” logging in again, update login_counts so “admin” now maps to 2.
# 7. Add “guest” to login_counts with a value of 1.
# 8. Print the final login_counts dictionary.

"""Føler mig angrebet når jeg ikke må bruge loops endnu... :D"""

unique_ips = set([])

unique_ips.add(logins[0]["ip"])
unique_ips.add(logins[1]["ip"])
unique_ips.add(logins[2]["ip"])

print(f"unique ips: {unique_ips}\nThat's {len(unique_ips)} ip's")

login_counts = {}

login_counts[logins[0]["user"]] = 1
login_counts[logins[1]["user"]] = 2
login_counts[logins[2]["user"]] = 1

print(f"login count after all events: {login_counts}")



print(splitter)
"""--------------------------------------------------------"""

# Type Conversion Practice
# Python often needs to convert between types. Try the following:
# Your program must now do the following:
# 1. Create a variable age_text with the value “25” (as a string). Convert
# it to an integer, store it in age, and print age + 1.
# 2. Create a list numbers = [1, 2, 3]. Convert it into a tuple called
# numbers_tuple and print it.
# 3. Convert numbers_tuple back into a list and print it.
# 4. Create a variable score = 95. Convert it into a string, concatenate it
# with the text “points”, and print the result.
# 5. Use type() to print the type of age, numbers_tuple, and score

age_text = "25"
age = int(age_text)
print(f"age in int {age+1}")

numbers = [1, 2, 3]
numbers_tuple = tuple(numbers)
print(f"list converted to tuple {numbers_tuple}")
print(f"and back to list {list(numbers_tuple)}")

score = 95
score_text = str(score) + " points"
print(f"this is a string: {score_text}")

print(f"type of age {type(age)}\ntype of numbers_tuple {type(numbers_tuple)}\ntype of score {type(score)}")



print(splitter)
"""--------------------------------------------------------"""

# Nested Data - Server Fleet Report
# You are managing a small fleet of servers. Each server is a dictionary, and all servers are stored together in a list:
servers = [
           {"name": "srv01", "os": "Linux", "open_ports": [22, 80, 443]},
           {"name": "srv02", "os": "Windows", "open_ports": [3389, 445]},
           {"name": "srv03", "os": "Linux", "open_ports": [22]}
           ]
# Your program must now do the following (access items manually, e.g. servers[0], servers[1] – no for loops yet):
# 1. Print the “name” of the second server in the list using indexing plus key access.
# 2. Print the first open port of servers[0] (hint: you’ll need to index the list AND the nested list).
# 3. Add the port 8080 to servers[0]’s open_ports list using .append().
# 4. Change the “os” of servers[2] to “Windows”.
# 5. Add a brand new key “patched” with value True to servers[1].
# 6. Add a fourth server dictionary of your own to the servers list, with a “name”, “os”, and “open_ports” list.
# 7. Print how many servers are now in the list using len().
# 8. Print how many open ports servers[0] has, using len() on its open_ports list.
# Bonus – Tuple with lists: Create a tuple called backup_snapshot = (servers[0]["open_ports"], servers[2]["open_ports"]) and print it. Then
# append a port to servers[0]["open_ports"] again and print backup_snapshot a second time. Discuss: why did the tuple’s contents change, even
# though tuples are immutable?

print(f"name of second server: {servers[1]["name"]}")
print(f"first open port on server 01: {servers[0]["open_ports"][0]}")
servers[0]["open_ports"].append(8080)
print(f"open ports on server 01: {servers[0]["open_ports"]}")
servers[2]["os"] = "Windows"
print(f"OS of server 03: {servers[2]["os"]}")
servers[1]["patched"] = True
print(f"Patched value of server 02: {servers[1]["patched"]}")
servers.append({"name": "srv04", "os": "MacOS", "open_ports": [22, 80, 443, 3389]})
print(f"My own entrie of server 04: {servers[3]}")
print(f"there are {len(servers)} servers")
print(f"there are {len(servers[0]["open_ports"])} open ports on server 01")


"""BONUS PART"""
"""My description of why this happens"""
# Bonus: this works because backshow refrences the list in servers
# So when we call backup, it makes a refrence to whatever is in that list and makes the tuple
# If the tuple were hardcoded this wouldn't be possible
backup_snapshot = (servers[0]["open_ports"], servers[2]["open_ports"])
print(f"backup: {backup_snapshot}")
servers[0]["open_ports"].append(8081)
print(f"backup: {backup_snapshot}")



print(splitter)
"""--------------------------------------------------------"""

# Vulnerability Tracker
# Your team tracks known vulnerabilities by severity level. Each severity maps to a list of CVE IDs:
vulnerabilities = {
                   "critical": ["CVE-2024-1111", "CVE-2024-2222"],
                   "high": ["CVE-2024-3333"],
                   "medium": []
                   }
# Your program must now do the following:
# 1. Print the list of critical vulnerabilities using key access.
# 2. Add “CVE-2024-4444” to the “high” list using .append().
# 3. Print how many critical vulnerabilities there are using len().
# 4. Add a new key “low” to the dictionary with an empty list as its value.
# 5. Add “CVE-2024-5555” to the “medium” list.
# 6. Check whether “CVE-2024-3333” is in the “high” list using in, and print the result.
# 7. Combine all CVEs from “critical” and “high” into one new list called top_priority using list concatenation (+), and print
# it.
# 8. Print the total number of tracked CVEs across all severities (add up the len() of each list manually)

print(f"This is critical!!! {vulnerabilities['critical']}")

vulnerabilities['high'].append("CVE-2024-4444")
print(f"This is high!! {vulnerabilities['high']}")

vulnerabilities['low'] = []
print(f"This is the dict: {vulnerabilities}")

vulnerabilities['medium'].append("CVE-2024-5555")
print(f"This is medium! {vulnerabilities['medium']}")

print(f"CVE-2024-3333 is in high: {"CVE-2024-3333" in vulnerabilities['high']}")

top_priority = vulnerabilities['critical'] + vulnerabilities['high']
print(f"This is top priority!!! {top_priority}")

total_vulnerabilities = len(vulnerabilities['critical']) + len(vulnerabilities['high']) + len(vulnerabilities['medium']) + len(vulnerabilities['low'])
print(f"There are {total_vulnerabilities} vulnerabilities")



print(splitter)
"""--------------------------------------------------------"""

# Challenge: Password Strength Check
# Next week you'll learn control flow properly – but you've already seen
# a taste of if statements. Give this a try:
password = "Cyber2026!"
# Your program must now do the following:
# 1. Create a boolean called long_enough that checks whether len(password) is at
# least 8.
# 2. Create a boolean called has_number that checks whether “2” is in password.
# 3. Using an if/else statement, print “Strong password” if both long_enough and
# has_number are True, otherwise print “Weak password”.
# 4. Bonus: add an elif branch that prints “Medium password” if only one of the two
# checks passes.

long_enough = True if len(password) >= 8 else False
has_number = True if "2" in password else False
if long_enough and has_number: print("Strong password")
elif long_enough or has_number: print("Medium password")
else: print("Weak password")



print(splitter)
"""--------------------------------------------------------"""

# Challenge: Looping Through Blocked Ports
# A for loop lets you go through a list automatically, instead of
# one item at a time.
blocked_ports = [21, 23, 135, 445, 3389]
# Your program must now do the following:
# 1. Write a for loop that prints each port in blocked_ports.
# 2. Inside the loop, use an if statement to also print “Risky port!”
# whenever the port is 23 or 3389.
# 3. After the loop, print how many ports were checked in total, using
# len().

for port in blocked_ports:
    print(f"This port is blocked: {port}")
    if port == 23 or port == 3389: print("Risky port!")

print(f"ports checked: {len(blocked_ports)}")



print(splitter)
"""--------------------------------------------------------"""

# Challenge: Simulated Login Attempts
# A while loop keeps running as long as a condition stays True. Use
# one to simulate a simple login system.
correct_password = "letmein"
attempts = 0
# Your program must now do the following:
# 1. Write a while loop that keeps asking for input() as long as attempts is
# less than 3 and the entered password doesn't match correct_password.
# 2. Each time the loop runs, increase attempts by 1.
# 3. After the loop, print “Access granted” if the password matched, or
# “Account locked” if the attempts ran out.

while attempts < 3:
    if input("Password: ") == correct_password: break
    else: attempts += 1

if attempts < 3: print("Access granted")
else: print("Account locked")



print(splitter)
"""--------------------------------------------------------"""

# Challenge: Flagging Suspicious Users
# Combine everything you know with a for loop and an if statement.
user_roles = {"liban": "admin", "guest1": "read-only", "guest2": "read-only", "alex": "moderator"}
# Your program must now do the following:
# 1. Write a for loop that goes through each key in user_roles.
# 2. Inside the loop, use an if statement to print “Guest account: ”
# followed by the username, whenever the role is “read-only”.
# 3. Bonus: keep a count of how many guest accounts were found and print the
# total after the loop.

guest_account_counter = 0

for role in user_roles:
    if user_roles[role] == "read-only":
        print(f"Guest account: {role}")
        guest_account_counter += 1

print(f"There were {guest_account_counter} guest accounts")

